spring:
  application:
    name: traffic-service
  datasource:
    url: jdbc:mysql://localhost:13306/trafficdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      lifecycle-management: start-and-stop

server:
  port: 8080
